id = "trident"
name = "Trident"
description = "Trident â€” universal language for provable computation"
version = "0.1.0"
schema_version = 1
authors = ["mastercyb"]

[lib]
kind = "Rust"
version = "0.7.0"

[grammars.trident]
repository = "https://github.com/mastercyb/trident"
path = "tree-sitter"
rev = "77c2e400dbe5033f86bc6bfe6a2dc6154bc6dbbe"

[language_servers.trident-lsp]
name = "Trident LSP"
languages = ["Trident"]
